# Generated by Django 5.1.1 on 2026-07-02 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('itinerary_json', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, hyphens, and underscores only.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
            ],
            options={
                'ordering': ['language_code', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['enabled'], name='pois_itiner_enabled_b9255f_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['created_at'], name='pois_itiner_created_003486_idx'),
        ),
        migrations.AddField(
            model_name='itinerarytranslation',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.itinerary'),
        ),
        migrations.AddIndex(
            model_name='itinerarytranslation',
            index=models.Index(fields=['language_code'], name='pois_itiner_languag_78e993_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytranslation',
            index=models.Index(fields=['slug'], name='pois_itiner_slug_44aa42_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarytranslation',
            constraint=models.UniqueConstraint(fields=('itinerary', 'language_code'), name='unique_itinerary_translation_language'),
        ),
    ]
