# Generated by Django 5.1.1 on 2026-07-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_itinerary_itinerarytranslation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['id'], 'verbose_name_plural': 'itineraries'},
        ),
    ]
