# Generated by Django 5.1.1 on 2026-07-02 15:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_alter_itinerary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, hyphens, and underscores only.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
            ],
            options={
                'ordering': ['language_code', 'title'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='stage_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['enabled'], name='pois_route_enabled_82f37c_idx'), models.Index(fields=['created_at'], name='pois_route_created_d3f1bc_idx')],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries', to='pois.route'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['route', 'stage_number'], name='pois_itiner_route_i_fa28e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerary',
            constraint=models.UniqueConstraint(condition=models.Q(('route__isnull', False), ('stage_number__isnull', False)), fields=('route', 'stage_number'), name='unique_itinerary_stage_per_route'),
        ),
        migrations.AddField(
            model_name='routetranslation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.route'),
        ),
        migrations.AddIndex(
            model_name='routetranslation',
            index=models.Index(fields=['language_code'], name='pois_routet_languag_f87521_idx'),
        ),
        migrations.AddIndex(
            model_name='routetranslation',
            index=models.Index(fields=['slug'], name='pois_routet_slug_b8569e_idx'),
        ),
        migrations.AddConstraint(
            model_name='routetranslation',
            constraint=models.UniqueConstraint(fields=('route', 'language_code'), name='unique_route_translation_language'),
        ),
        migrations.AddConstraint(
            model_name='routetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'slug'), name='unique_route_translation_slug_per_language'),
        ),
    ]
