# Generated by Django 5.1.1 on 2026-07-02 22:09

from django.db import migrations, models


def set_reference_translations(apps, schema_editor):
    translation_models = [
        ("POITranslation", "poi_id"),
        ("RouteTranslation", "route_id"),
        ("ItineraryTranslation", "itinerary_id"),
    ]
    for model_name, parent_field in translation_models:
        translation_model = apps.get_model("pois", model_name)
        parent_ids = translation_model.objects.values_list(parent_field, flat=True).distinct()
        for parent_id in parent_ids:
            reference = (
                translation_model.objects.filter(**{parent_field: parent_id})
                .order_by("language_code", "title", "id")
                .first()
            )
            if reference:
                reference.is_reference = True
                reference.save(update_fields=["is_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0004_routetranslation_itinerary_stage_number_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytranslation',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poitranslation',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routetranslation',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_reference_translations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='itinerarytranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('itinerary',), name='unique_reference_itinerary_translation'),
        ),
        migrations.AddConstraint(
            model_name='poitranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('poi',), name='unique_reference_poi_translation'),
        ),
        migrations.AddConstraint(
            model_name='routetranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('route',), name='unique_reference_route_translation'),
        ),
    ]
