# Generated by Django 5.1.1 on 2026-07-03 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0005_itinerarytranslation_is_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message="Use ISO 3166-1 alpha-2 country codes like 'ES', 'PT', or 'FR'.", regex='^[A-Z]{2}$')]),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['country_code'], name='pois_poi_country_27d5ea_idx'),
        ),
    ]
