# Generated by Django 5.1.1 on 2026-07-06 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_itinerary_route_stages(apps, schema_editor):
    Itinerary = apps.get_model('pois', 'Itinerary')
    RouteStage = apps.get_model('pois', 'RouteStage')
    memberships = []
    for itinerary in Itinerary.objects.exclude(route_id=None).exclude(stage_number=None):
        memberships.append(
            RouteStage(
                route_id=itinerary.route_id,
                itinerary_id=itinerary.id,
                stage_number=itinerary.stage_number,
            )
        )
    RouteStage.objects.bulk_create(memberships)


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0006_poi_country_code_poi_pois_poi_country_27d5ea_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route', 'stage_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='routestage',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stages', to='pois.itinerary'),
        ),
        migrations.AddField(
            model_name='routestage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pois.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='itineraries',
            field=models.ManyToManyField(blank=True, related_name='routes', through='pois.RouteStage', to='pois.itinerary'),
        ),
        migrations.RunPython(copy_itinerary_route_stages, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='itinerary',
            name='unique_itinerary_stage_per_route',
        ),
        migrations.RemoveIndex(
            model_name='itinerary',
            name='pois_itiner_route_i_fa28e1_idx',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='route',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='stage_number',
        ),
        migrations.AddIndex(
            model_name='routestage',
            index=models.Index(fields=['route', 'stage_number'], name='pois_routes_route_i_4eee34_idx'),
        ),
        migrations.AddIndex(
            model_name='routestage',
            index=models.Index(fields=['itinerary'], name='pois_routes_itinera_0e5247_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestage',
            constraint=models.UniqueConstraint(fields=('route', 'stage_number'), name='unique_stage_number_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routestage',
            constraint=models.UniqueConstraint(fields=('route', 'itinerary'), name='unique_itinerary_per_route'),
        ),
    ]
