# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pois", "0007_routestage_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="POIImage",
            new_name="POIMedia",
        ),
        migrations.RemoveConstraint(
            model_name="poimedia",
            name="unique_primary_image_per_poi",
        ),
        migrations.RemoveIndex(
            model_name="poimedia",
            name="pois_poiima_positio_8f58b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="poimedia",
            name="pois_poiima_is_prim_9a1275_idx",
        ),
        migrations.RenameField(
            model_name="poimedia",
            old_name="image_url",
            new_name="url",
        ),
        migrations.AddField(
            model_name="poimedia",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                    ("link", "Link"),
                    ("other", "Other"),
                ],
                default="image",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="poimedia",
            name="poi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="pois.poi",
            ),
        ),
        migrations.AddIndex(
            model_name="poimedia",
            index=models.Index(fields=["media_type"], name="pois_poimed_media_t_f87a71_idx"),
        ),
        migrations.AddIndex(
            model_name="poimedia",
            index=models.Index(fields=["position"], name="pois_poimed_positio_2be32b_idx"),
        ),
        migrations.AddIndex(
            model_name="poimedia",
            index=models.Index(fields=["is_primary"], name="pois_poimed_is_prim_565904_idx"),
        ),
        migrations.AddConstraint(
            model_name="poimedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("poi",),
                name="unique_primary_media_per_poi",
            ),
        ),
    ]
