# Generated by Django 5.1.1 on 2026-07-13 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0009_poimedia_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIMediaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('caption', models.TextField(blank=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.poimedia')),
            ],
            options={
                'ordering': ['language_code'],
                'indexes': [models.Index(fields=['language_code'], name='pois_poimtr_languag_12b70f_idx')],
                'constraints': [models.UniqueConstraint(fields=('media', 'language_code'), name='unique_poi_media_translation_language')],
            },
        ),
    ]
