# Generated by Django 5.1.1 on 2026-07-13 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0010_poimediatranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link'), ('other', 'Other')], default='image', max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='itinerary-media/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pois.itinerary')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryMediaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('caption', models.TextField(blank=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.itinerarymedia')),
            ],
            options={
                'ordering': ['language_code'],
            },
        ),
        migrations.CreateModel(
            name='RouteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link'), ('other', 'Other')], default='image', max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='route-media/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pois.route')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RouteMediaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('caption', models.TextField(blank=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.routemedia')),
            ],
            options={
                'ordering': ['language_code'],
            },
        ),
        migrations.AddIndex(
            model_name='itinerarymedia',
            index=models.Index(fields=['media_type'], name='pois_itinme_media_t_d2f5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarymedia',
            index=models.Index(fields=['position'], name='pois_itinme_positio_40b1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarymedia',
            index=models.Index(fields=['is_primary'], name='pois_itinme_is_prim_0d5744_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarymedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('itinerary',), name='unique_primary_media_per_itinerary'),
        ),
        migrations.AddIndex(
            model_name='itinerarymediatranslation',
            index=models.Index(fields=['language_code'], name='pois_itinmt_languag_ae9e60_idx'),
        ),
        migrations.AddConstraint(
            model_name='itinerarymediatranslation',
            constraint=models.UniqueConstraint(fields=('media', 'language_code'), name='unique_itinerary_media_translation_language'),
        ),
        migrations.AddIndex(
            model_name='routemedia',
            index=models.Index(fields=['media_type'], name='pois_routem_media_t_983cab_idx'),
        ),
        migrations.AddIndex(
            model_name='routemedia',
            index=models.Index(fields=['position'], name='pois_routem_positio_102b54_idx'),
        ),
        migrations.AddIndex(
            model_name='routemedia',
            index=models.Index(fields=['is_primary'], name='pois_routem_is_prim_481f2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='routemedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('route',), name='unique_primary_media_per_route'),
        ),
        migrations.AddIndex(
            model_name='routemediatranslation',
            index=models.Index(fields=['language_code'], name='pois_routmt_languag_68e5c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='routemediatranslation',
            constraint=models.UniqueConstraint(fields=('media', 'language_code'), name='unique_route_media_translation_language'),
        ),
    ]
