# Generated by Django 5.1.1 on 2026-08-31 12:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0013_poi_footprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, hyphens, and underscores only.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'fest categories',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message="Use ISO 3166-1 alpha-2 country codes like 'ES', 'PT', or 'FR'.", regex='^[A-Z]{2}$')])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('footprint', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='fests', to='pois.festcategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FestCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.festcategory')),
            ],
            options={
                'ordering': ['language_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FestEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='pois.fest')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='FestDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='pois.festedition')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FestMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link'), ('other', 'Other')], default='image', max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='fest-media/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pois.fest')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FestMediaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('caption', models.TextField(blank=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.festmedia')),
            ],
            options={
                'ordering': ['language_code'],
            },
        ),
        migrations.CreateModel(
            name='FestTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="Use ISO language codes like 'en', 'es', or 'pt-PT'.", regex='^[a-z]{2}(-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, hyphens, and underscores only.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('is_reference', models.BooleanField(default=False)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pois.fest')),
            ],
            options={
                'ordering': ['language_code', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='fest',
            index=models.Index(fields=['enabled'], name='pois_fest_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='fest',
            index=models.Index(fields=['country_code'], name='pois_fest_country_idx'),
        ),
        migrations.AddIndex(
            model_name='fest',
            index=models.Index(fields=['created_at'], name='pois_fest_created_idx'),
        ),
        migrations.AddIndex(
            model_name='festcategorytranslation',
            index=models.Index(fields=['language_code'], name='pois_festcat_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='festcategorytranslation',
            constraint=models.UniqueConstraint(fields=('category', 'language_code'), name='unique_fest_cat_trans_lang'),
        ),
        migrations.AddIndex(
            model_name='festedition',
            index=models.Index(fields=['year'], name='pois_fested_year_idx'),
        ),
        migrations.AddIndex(
            model_name='festedition',
            index=models.Index(fields=['is_cancelled'], name='pois_fested_cancel_idx'),
        ),
        migrations.AddConstraint(
            model_name='festedition',
            constraint=models.UniqueConstraint(fields=('fest', 'year'), name='unique_fest_edition_year'),
        ),
        migrations.AddIndex(
            model_name='festdate',
            index=models.Index(fields=['date'], name='pois_festdate_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='festdate',
            constraint=models.UniqueConstraint(fields=('edition', 'date'), name='unique_fest_edition_date'),
        ),
        migrations.AddIndex(
            model_name='festmedia',
            index=models.Index(fields=['media_type'], name='pois_festmed_type_idx'),
        ),
        migrations.AddIndex(
            model_name='festmedia',
            index=models.Index(fields=['position'], name='pois_festmed_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='festmedia',
            index=models.Index(fields=['is_primary'], name='pois_festmed_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='festmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('fest',), name='unique_primary_media_per_fest'),
        ),
        migrations.AddIndex(
            model_name='festmediatranslation',
            index=models.Index(fields=['language_code'], name='pois_festmtr_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='festmediatranslation',
            constraint=models.UniqueConstraint(fields=('media', 'language_code'), name='unique_fest_media_trans_lang'),
        ),
        migrations.AddIndex(
            model_name='festtranslation',
            index=models.Index(fields=['language_code'], name='pois_festtr_lang_idx'),
        ),
        migrations.AddIndex(
            model_name='festtranslation',
            index=models.Index(fields=['slug'], name='pois_festtr_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='festtranslation',
            constraint=models.UniqueConstraint(fields=('fest', 'language_code'), name='unique_fest_translation_lang'),
        ),
        migrations.AddConstraint(
            model_name='festtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'slug'), name='unique_fest_slug_per_lang'),
        ),
        migrations.AddConstraint(
            model_name='festtranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('fest',), name='unique_reference_fest_trans'),
        ),
    ]
