# Generated by Django 5.1.1 on 2026-07-14 08:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('route', 'Route'), ('itinerary', 'Itinerary'), ('poi', 'POI'), ('category', 'Category'), ('media', 'Media')], max_length=20)),
                ('subject_id', models.PositiveBigIntegerField()),
                ('predicate', models.CharField(max_length=120)),
                ('object_uri', models.URLField(max_length=1000)),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('source_field', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(default='manual', max_length=80)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('review_status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='candidate', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_type', 'subject_id', 'predicate', 'object_uri'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='eccch_expor_subject_0f1eda_idx'), models.Index(fields=['predicate'], name='eccch_expor_predica_bec698_idx'), models.Index(fields=['object_uri'], name='eccch_expor_object__22af50_idx'), models.Index(fields=['review_status'], name='eccch_expor_review__e4eb7d_idx'), models.Index(fields=['method'], name='eccch_expor_method_d0193a_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id', 'predicate', 'object_uri', 'source_field', 'method'), name='unique_eccch_semantic_annotation')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('route', 'Route'), ('itinerary', 'Itinerary'), ('poi', 'POI'), ('category', 'Category'), ('media', 'Media')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField()),
                ('vocabulary', models.CharField(max_length=80)),
                ('target_uri', models.URLField(max_length=1000)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('relation', models.CharField(choices=[('exactMatch', 'Exact match'), ('closeMatch', 'Close match'), ('broadMatch', 'Broad match'), ('narrowMatch', 'Narrow match'), ('relatedMatch', 'Related match')], default='closeMatch', max_length=20)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_type', 'source_id', 'vocabulary', 'target_uri'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='eccch_expor_source__ecdecc_idx'), models.Index(fields=['vocabulary'], name='eccch_expor_vocabul_2c683e_idx'), models.Index(fields=['target_uri'], name='eccch_expor_target__113071_idx'), models.Index(fields=['reviewed'], name='eccch_expor_reviewe_444fa1_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'vocabulary', 'target_uri', 'relation'), name='unique_eccch_vocabulary_mapping')],
            },
        ),
    ]
